name: maptrack
description: A new Flutter project.
# publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
    
  google_maps_place_picker_mb: ^2.0.0-mb.22
  flutter_polyline_points: ^1.0.0
  google_maps_widget: ^1.0.5+1
  google_maps_flutter: ^2.2.3
  geocoding: ^2.0.5
  location: ^4.4.0
  
  
  # provider: ^6.0.5
  # geolocator: ^9.0.2
  # google_polyline_algorithm: ^3.1.0
  # shimmer: ^2.0.0
  # url_launcher: ^6.1.7
  # lottie: ^2.0.0
  # flutter_rating_bar: ^4.0.1
  # touch_indicator: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #         weight: 700
