name: location_example
description: Demonstrates how to use the location plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.4
  google_maps_flutter_android: ^2.4.9
  google_maps_flutter_platform_interface: ^2.2.6
  location:
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
